version: "3.8"

services:
  backend1:
    build: ./backend1
    container_name: backend1
    ports:
      - "5001:5000"

  backend2:
    build: ./backend2
    container_name: backend2
    ports:
      - "5002:5000"

  nginx:
    build: ./nginx
    container_name: nginx_lb
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
